# Generated by Django 4.1.4 on 2023-01-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_asset_pair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
