# Generated by Django 4.1.4 on 2023-01-18 20:48
from django.db import connection
from django.db import migrations


def insert_data(apps, schema_editor):
    sql = """
    insert into api_asset(name, symbol, type) values ('Tether', 'USDT', 'crypto') ON CONFLICT DO NOTHING;
    insert into api_asset(name, symbol, type) values ('Bitcoin', 'BTC', 'crypto') ON CONFLICT DO NOTHING;
    insert into api_asset(name, symbol, type) values ('Ethereum', 'ETH', 'crypto') ON CONFLICT DO NOTHING;
    insert into api_asset(name, symbol, type) values ('BNB', 'BNB', 'crypto') ON CONFLICT DO NOTHING;
    insert into api_asset(name, symbol, type) values ('Mina Protocol', 'MINA', 'crypto') ON CONFLICT DO NOTHING;
    insert into api_asset(name, symbol, type) values ('Cosmos', 'ATOM', 'crypto') ON CONFLICT DO NOTHING;
    insert into api_asset(name, symbol, type) values ('Polkadot', 'DOT', 'crypto') ON CONFLICT DO NOTHING;

    insert into api_assetpair(base_asset_id, quote_asset_id) values (2, 1) ON CONFLICT DO NOTHING;
    insert into api_assetpair(base_asset_id, quote_asset_id) values (3, 1) ON CONFLICT DO NOTHING;
    insert into api_assetpair(base_asset_id, quote_asset_id) values (4, 1) ON CONFLICT DO NOTHING;
    insert into api_assetpair(base_asset_id, quote_asset_id) values (5, 1) ON CONFLICT DO NOTHING;
    insert into api_assetpair(base_asset_id, quote_asset_id) values (6, 1) ON CONFLICT DO NOTHING;
    insert into api_assetpair(base_asset_id, quote_asset_id) values (7, 1) ON CONFLICT DO NOTHING; 
    """

    with connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_price_alter_order_quantity'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
