# Generated by Django 4.1.4 on 2023-01-01 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='asset_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_pair', to='core.assetpair'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assetpair')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
