# Generated by Django 4.1.4 on 2023-01-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_asset_pair_alter_order_status_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'PartiallyFilled'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
