# Generated by Django 4.1.4 on 2023-01-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_created_at_order_updated_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
