# Generated by Django 4.1.4 on 2023-01-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asset_name_alter_asset_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
